import type { WorldEntry } from "./worldStore";

// Static sample worlds — full panos live in public/sample-worlds/
// and lightweight card thumbnails live in public/sample-worlds/thumbs/.
export const SAMPLE_WORLDS: WorldEntry[] = [
  {
    id: "sample_tokyo_night",
    panoPath: "/sample-worlds/tokyo-night.jpg",
    thumbnailPath: "/sample-worlds/thumbs/tokyo-night.jpg",
    parameters: {
      location: "Tokyo, Japan",
      timeOfDay: "night",
      decade: "Today",
      placeType: "street",
      weather: "clear",
      crowd: "busy",
    },
    prompt: "",
    createdAt: 1,
  },
  {
    id: "sample_paris_golden",
    panoPath: "/sample-worlds/paris-golden-hour.jpg",
    thumbnailPath: "/sample-worlds/thumbs/paris-golden-hour.jpg",
    parameters: {
      location: "Paris, France",
      timeOfDay: "golden hour",
      decade: "Today",
      placeType: "street",
      weather: "clear",
      crowd: "moderate",
    },
    prompt: "",
    createdAt: 2,
  },
  {
    id: "sample_havana_1970s",
    panoPath: "/sample-worlds/havana-1970s.jpg",
    thumbnailPath: "/sample-worlds/thumbs/havana-1970s.jpg",
    parameters: {
      location: "Havana, Cuba",
      timeOfDay: "noon",
      decade: "1970s",
      placeType: "street",
      weather: "clear",
      crowd: "few people",
    },
    prompt: "",
    createdAt: 3,
  },
  {
    id: "sample_marrakech_market",
    panoPath: "/sample-worlds/marrakech-market.jpg",
    thumbnailPath: "/sample-worlds/thumbs/marrakech-market.jpg",
    parameters: {
      location: "Marrakech, Morocco",
      timeOfDay: "morning",
      decade: "Today",
      placeType: "market",
      weather: "hazy",
      crowd: "busy",
    },
    prompt: "",
    createdAt: 4,
  },
  {
    id: "sample_reykjavik_snow",
    panoPath: "/sample-worlds/reykjavik-snow.jpg",
    thumbnailPath: "/sample-worlds/thumbs/reykjavik-snow.jpg",
    parameters: {
      location: "Reykjavik, Iceland",
      timeOfDay: "dawn",
      decade: "Today",
      placeType: "street",
      weather: "snow",
      crowd: "empty",
    },
    prompt: "",
    createdAt: 5,
  },
  {
    id: "sample_rome_1960s",
    panoPath: "/sample-worlds/rome-1960s.jpg",
    thumbnailPath: "/sample-worlds/thumbs/rome-1960s.jpg",
    parameters: {
      location: "Rome, Italy",
      timeOfDay: "afternoon",
      decade: "1960s",
      placeType: "piazza",
      weather: "sunny",
      crowd: "moderate",
    },
    prompt: "",
    createdAt: 6,
  },
  {
    id: "sample_new_york_1980s",
    panoPath: "/sample-worlds/new-york-1980s.jpg",
    thumbnailPath: "/sample-worlds/thumbs/new-york-1980s.jpg",
    parameters: {
      location: "New York City, USA",
      timeOfDay: "afternoon",
      decade: "1980s",
      placeType: "street",
      weather: "clear",
      crowd: "busy",
    },
    prompt: "",
    createdAt: 7,
  },
  {
    id: "sample_berlin_1990s",
    panoPath: "/sample-worlds/berlin-1990s.jpg",
    thumbnailPath: "/sample-worlds/thumbs/berlin-1990s.jpg",
    parameters: {
      location: "Berlin, Germany",
      timeOfDay: "afternoon",
      decade: "1990s",
      placeType: "street",
      weather: "overcast",
      crowd: "few people",
    },
    prompt: "",
    createdAt: 8,
  },
];
